name: CI - Lint, Test, Build Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Cache pip packages
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install dependencies + essential packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pre-commit pandas numpy scikit-learn

      # 5️⃣ Run code formatting & lint checks
      - name: Run pre-commit (Black/Ruff)
        run: pre-commit run --all-files || true

      # 6️⃣ Run unit tests
      - name: Run tests
        run: |
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh

      # 7️⃣ Smoke train (synthetic data)
      - name: Smoke train (synthetic data)
        run: |
          python -m src.bigbasket.train --outdir models
          ls -l models

      # 8️⃣ Upload trained models as artifact
      - name: Upload trained models
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: models/

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t bigbasket-pipeline:latest .

      # Optional: push to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Push Docker image
      #   run: |
      #     docker tag bigbasket-pipeline:latest ${{ secrets.DOCKERHUB_USERNAME }}/bigbasket-pipeline:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/bigbasket-pipeline:latest